spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/security_auth
spring.datasource.username=root
spring.datasource.password=Babuprasanth@05@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8081

role.admin = ADMIN
role.user = USER